config/routes.rb
Rails.application.routes.draw do
  resources :tweets, only: [:index, :new, :create, :destroy]
  #resources にて自動でルートを設定できる→　indexとnewコントローラーに対し作成
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/tweet.rb
class Tweet < ApplicationRecord
  validates :text, presence: true
  #バリテーション　空のデータは受け取らない処理
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
end

app/controllers/tweets_controller.rb
class TweetsController < ApplicationController

  def index
    @tweets = Tweet.all
    #＠tweets変数に　Tweetモデルの全てを扱えるようにする処理
  end

  def new
    @tweet = Tweet.new
    #@tweet 変数に入ったものは、Tweetモデルクラスに追加されるnewメソッドを適応される。
  end

  def create
    Tweet.create(tweet_params)
    #tweetモデルを作る処理（tweet_paramsはプライベートに記載）
  end

  def destroy
    tweet = Tweet.find(params[:id])
    # レスポンスにて受け取ったHTML　DELETEとtweetのIDをもつハッシュをTweetモデルから検索し特定する。
    #　そのハッシュデータをtweet変数に入れる
    tweet.destroy
    # tweet変数に入れられたハッシュを消すメソッドを実施する
  end

  private
  def tweet_params
    params.require(:tweet).permit(:name, :image, :text)
    #ストロングパラメータ　require（:tweet）とすることで、レスポンスで受け取る各データの内、tweetに関する内容を選ぶ。
    #その後、tweetに入っている中の、name,image,textを受け取るとする。
  end


end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/tweets_helper.rb
module TweetsHelper
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>Pictweet</title>
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>
    <%= stylesheet_link_tag 'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_pack_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>
  <body>
    <header class="header">
      <div class="header__bar row">
        <h1 class="grid-6"><a href="/">PicTweet</a></h1>
        <div class="user_nav grid-6">
          <a class="post" href="/tweets/new">投稿する</a>
        </div>
      </div>
    </header>
      <%= yield %>
    <footer>
      <p>
        Copyright PicTweet 2019.
      </p>
    </footer>
  </body>
</html>

app/views/tweets/create.html.erb
<div class="contents row">
  <div class="success">
    <h3>
      投稿が完了しました。
    </h3>
    <a class="btn" href="/tweets">投稿一覧へ戻る</a>
  </div>
</div>

app/views/tweets/destroy.html.erb
<div class="contents row">
  <div class="success">
    <h3>
      削除が完了しました。
    </h3>
    <a class="btn" href="/tweets">投稿一覧へ戻る</a>
  </div>
</div>

app/views/tweets/index.html.erb
<div class="contents row">
  <% @tweets.each do |tweet| %>
  <%# @tweetに格納されたハッシュを配列回数,変数tweetに入れ実施する%>
    <div class="content_post" style="background-image: url(<%= tweet.image %>);">
    <%# HTMLでstyleのbackground-imageを指定する、URLは繰り返し配列ハッシュのうち、key->imageを取り出す%>
    <div class="more">
        <span><%= image_tag 'arrow_top.png' %></span>
        <%# ????????????????要確認%>
        <ul class="more_list">
          <li>
            <%= link_to '削除', tweet_path(tweet.id), method: :delete %>
            <%# link_to '削除', "/tweets/#{tweet.id}", method: :delete %>
            <%#ボタンに「削除」と記載、リクエストとして、削除ボタンを押した配列ハッシュのIDとdeleteとの情報をリクエストに送信する%>
          </li>
        </ul>
      </div>
      <p><%= tweet.text %></p>
      <span class="name">
        <%= tweet.name %>
      </span>
    </div>
  <% end %>
</div>

app/views/tweets/new.html.erb
<div class="contents row">
  <div class="container">
    <%= form_with(model: @tweet, local: true) do |form| %>
    <%#＠tweetに送ることによりコントローラーでtweetモデルクラスに追加することができる%>
      <h3>
        投稿する
      </h3>
      <%= form.text_field :name, placeholder: "Nickname" %>
      <%= form.text_field :image, placeholder: "Image Url" %>
      <%= form.text_area :text, placeholder: "text" , rows: "10" %>
      <%= form.submit "SEND" %>
    <% end %>
  </div>
</div>